### ISSUE TITLE
Consider supporting `NO_COLOR` env var

### ISSUE THREAD

**Issue by mainrs** [jam1garner/owo-colors#11]
https://no-color.org/
A lot of popular CLIs (GitHub CLI) and libraries (colored) do have support for it. Might be worth adding it to `owo-colors` as well :) I did take a look at the source code but there doesn't seem to be an easy way to "just ad a shim" implementation that returns the original string.

**Comment by SirWindfield** [comment]
A potential solution would be to check for he env var inside of `DynColor`'s and `Color`'s methods that write to the formatter:
https://github.com/jam1garner/owo-colors/blob/bec55f075575eed908e405637d2ee093727e1fd7/src/colors/xterm.rs#L21-L51

Is that a solution that you would be OK with? Maybe a feature flag would be appropriate, as it adds some overhead (although it should be fairly minimal).

**Comment by jam1garner** [comment]
I'd accept it under a feature flag, I'd propose something like:

* `no-color` - a feature for disabling all ansi codes at compile time
* `env-no-color` - a feature that, when enabled, would allow setting NO_COLOR to disable colors. I'd recommend looking at colored to see how it handles it since it supposedly has support. I'd prefer having full compatibility with their implementation if possible.

neither feature would be on by default

**Comment by jam1garner** [comment]
@mainrs This feature has now been added on master via `OwoColorize::if_supports_colors`, closing.
